repos:
- repo: local
  hooks:
    - id: protoc-generate-resources
      name: Protoc generate resources
      always_run: true
      entry: protoc
      args: ["--proto_path=../apis", "--proto_path=./v1", "--go_out=./", "--validate_out=lang=go:.", "mylostid.proto"]
      language: system
      types: [bash]
    - id: protoc-generate-servers
      name: Protoc generate Servers
      always_run: true
      entry: protoc
      args: ["--proto_path=../apis", "--proto_path=./v1", "mylostid.proto", "--go-grpc_out=./"]
      language: system
      types: [bash]
    - id: protoc-generate-mocks
      name: Protoc generate Mocks
      always_run: true
      entry: mockgen
      args: ["-source=mylostid_grpc.pb.go", "-self_package=github.com/antinvestor/service-mylostid-api", "-package=mylostidv1", "-destination=mylostid_grpc_mock.go"]
      language: system
      types: [bash]

- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: golangci-lint
    - id: go-unit-tests
    - id: go-build
    - id: go-mod-tidy